# Generated by Django 3.2.5 on 2021-08-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='unit',
            name='appartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_garages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='pets_allowed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='type_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_state_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
