# Generated by Django 3.2.5 on 2021-08-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210812_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit_type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='appartment_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_state_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
