# Generated by Django 3.2.5 on 2021-08-12 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit_state'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit_type'),
        ),
    ]
