# Generated by Django 3.2.5 on 2021-08-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210812_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='type_uuid',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_state_uuid',
        ),
        migrations.AlterField(
            model_name='unit',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='Uuid number'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('floor_space', models.CharField(max_length=20)),
                ('attachment_uuid', models.UUIDField()),
                ('address_uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.address')),
            ],
        ),
    ]
