# Generated by Django 3.2.5 on 2021-08-12 04:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210812_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('phone_number', models.DecimalField(decimal_places=8, max_digits=8)),
            ],
            options={
                'verbose_name': 'Employee',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Addres'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Propertie'},
        ),
        migrations.AlterModelOptions(
            name='unit_state',
            options={'verbose_name': 'Unit state'},
        ),
        migrations.AlterModelOptions(
            name='unit_type',
            options={'verbose_name': 'Unit type'},
        ),
        migrations.CreateModel(
            name='In_charge_of',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.employee')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.property')),
            ],
            options={
                'verbose_name': 'In charge of',
            },
        ),
    ]
