# Generated by Django 3.2.5 on 2021-08-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210812_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_attachment',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('geoence_file_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.file_attachment')),
            ],
        ),
    ]
