# Generated by Django 3.2.5 on 2021-08-12 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_file_attachment_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='geoence_file_uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.file_attachment'),
        ),
    ]
