# Generated by Django 3.2.5 on 2021-08-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_geofence_geoence_file_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AddField(
            model_name='geofence',
            name='property_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.property'),
        ),
        migrations.CreateModel(
            name='Propery_file_attachment',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('file_attachment_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.file_attachment')),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='attachment_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.propery_file_attachment'),
        ),
    ]
