# Generated by Django 3.2.5 on 2021-08-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210812_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Owner',
            },
        ),
        migrations.AlterModelOptions(
            name='file_attachment',
            options={'verbose_name': 'File attachment'},
        ),
        migrations.AlterField(
            model_name='property',
            name='attachment_uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.owner'),
        ),
    ]
