# Generated by Django 3.2.5 on 2021-08-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210812_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_type',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Contract type',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.contract'),
        ),
        migrations.CreateModel(
            name='Estate_contract',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('Contract_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.contract')),
                ('propery_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.property')),
            ],
            options={
                'verbose_name': 'Estate contract',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.contract_type'),
        ),
    ]
