# Generated by Django 3.2.5 on 2021-08-12 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20210812_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, null=True)),
                ('issued_by', models.CharField(max_length=20, null=True)),
                ('issued_to', models.CharField(max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('paid_date', models.DateTimeField(default=datetime.datetime.now)),
                ('tax_cut_percentage', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='Item_category',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_type',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Transaction type',
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_amount',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_frequency',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.transaction_type')),
            ],
            options={
                'verbose_name': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('default_price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('item_category_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.item_category')),
                ('supplier_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=20, null=True)),
                ('item_uuid', models.UUIDField()),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('invoice_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.invoice')),
            ],
            options={
                'verbose_name': 'Invoice_item',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.invoice'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tranaction_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.transaction'),
        ),
    ]
