# Generated by Django 3.2.5 on 2021-08-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20210812_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='item_category',
            options={'verbose_name': 'Item category'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier'},
        ),
    ]
